//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory contains a colon that is not part of a volume identifier: {0}..
        /// </summary>
        internal static string DirectoryColon {
            get {
                return ResourceManager.GetString("DirectoryColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist: {0}..
        /// </summary>
        internal static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is null..
        /// </summary>
        internal static string DirectoryNull {
            get {
                return ResourceManager.GetString("DirectoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permissions to monitor the given directory: {0}..
        /// </summary>
        internal static string DirectoryPermissions {
            get {
                return ResourceManager.GetString("DirectoryPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given directory is too long: {0}..
        /// </summary>
        internal static string DirectoryTooLong {
            get {
                return ResourceManager.GetString("DirectoryTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is zero length or contains invalid characters: {0}..
        /// </summary>
        internal static string DirectoryZeroInvalid {
            get {
                return ResourceManager.GetString("DirectoryZeroInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File pattern must only contain valid Windows File Name characters: {0}..
        /// </summary>
        internal static string FilePatternInvalidChars {
            get {
                return ResourceManager.GetString("FilePatternInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File pattern is null, white space or empty: {0}..
        /// </summary>
        internal static string FilePatternNullWSEmpty {
            get {
                return ResourceManager.GetString("FilePatternNullWSEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer is less than or equal to zero: {0}..
        /// </summary>
        internal static string TimerLessThanZero {
            get {
                return ResourceManager.GetString("TimerLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer is too large: {0}.  .
        /// </summary>
        internal static string TimerTooLarge {
            get {
                return ResourceManager.GetString("TimerTooLarge", resourceCulture);
            }
        }
    }
}
